# Generated by Django 2.0.5 on 2019-05-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('thumbnail', models.TextField()),
                ('publishdatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
