# Generated by Django 2.0.5 on 2019-05-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='videoid',
            field=models.TextField(null=True),
        ),
    ]
