# Generated by Django 2.0.5 on 2019-05-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190514_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='videoid',
            field=models.CharField(max_length=100),
        ),
    ]
