# Generated by Django 2.0.5 on 2019-05-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190515_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.TextField(db_index=True),
        ),
    ]
